### ISSUE TITLE
Error after upgrading to DNN 9.3.1

### ISSUE THREAD

**Issue by EPTamminga** [dnnconsulting/DnnC.Minimalist#6]
Skin /Portals/_default/Skins/DnnMinimalist/skin.ascx, kan niet worden geladen. Fout: C:\DDrive\Develop\hetvakantiehuisaanhetwater\Website\Portals\_default\Skins\DnnMinimalist\includes\profile-functions.ascx(1): error BC30456: GetEnabledLocales is geen lid van DotNetNuke.Services.Localization.Localization.

**Comment by dnnconsulting** [comment]
in the 'profile-functions.ascx for change the line:
<% if Localization.GetEnabledLocales().Count > 1 Then  %>
to
<% If LocaleController.Instance.GetLocales(PortalController.Instance.GetCurrentPortalSettings().PortalId).Count > 1 Then  %>

then the problem is solved
